### ISSUE TITLE
Guys, what is it with that noisy audio turned on with the presentation video?

### ISSUE THREAD

**Issue by cristifarcas** [oodesign/sketch-styler#1]

**Comment by oodesign** [comment]
Hi @cristifarcas ,

Yup, maybe the video music is a bit too loud, specially at the beginning. 
Team is now aware and hope that we can have a better version soon :) 

Thanks!

**Comment by cristifarcas** [comment]
Or, better leave it on mute and let users switch it on if they want on vimeo player. Audio on with auto-play can be very annoying if you don't expecting it.

Cheers!

On October 18, 2019 12:35:19 PM GMT+03:00, Oscar Oto <notifications@github.com> wrote:
>Hi @cristifarcas ,
>
>Yup, maybe the video music is a bit too loud, specially at the
>beginning. 
>Team is now aware and hope that we can have a better version soon :) 
>
>Thanks! 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/oodesign/sketch-styler/issues/1#issuecomment-543632530

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oodesign** [comment]
The video is set up to **not** autoplay. Is it playing as you open the page for you?

**Comment by cristifarcas** [comment]
Yep. On Firefox 69, Mac Mohave, it starts when the page is loading, if **Autoplay** permission is set to `Allow` in the browser. Is set to `Block` now :)
