### ISSUE TITLE
where do I put the License key?

### ISSUE THREAD

**Issue by StudioMorph** [oodesign/sketch-styler#24]
I have just purchased this plug-in. it doesn't seem to work and I cant find a place to add the license key

**Comment by oodesign** [comment]
Hi @DudaUK ,

Sketch Styler is a plugin for Sketch, and it may ask for activation the first time you try to run it in Sketch.

To install it:

- Download the latest version from Gumroad or [GitHub](https://github.com/oodesign/sketch-styler/releases/tag/v1.5.7).
- Unzip it, and double click on the ".sketchplugin" file.

To run Styler:

- Open Sketch (you may open a Sketch file you'd like to scan).
- Go to Plugins > Sketch Styler, and pick any of its variants to scan the selected layer, artboard, page, or the whole document.
- The first time you run Sketch Styler you may be prompted to activate the plugin. Type in your license key (that you can find in the receipt e-mail Gumroad sent you), and click on "Register". If the activation is successful Sketch Styler will appear right after.

Is any of the above not working properly for you?

**Comment by StudioMorph** [comment]
I have started sketch and working now.
Should have done that before asking for help.
Thank you for your prompt reply

Cheers,
José

**Comment by oodesign** [comment]
Oh! Glad to hear that!
And no worries at all. Just let us know if there is anything else we can help with. 😊
