### ISSUE TITLE
The plugin crashes Sketch in macOS Catalina

### ISSUE THREAD

**Issue by currocejudo** [oodesign/sketch-styler#3]
Just installed Sketch Styler 1.3.1
No other plugin installed in a Sketch 59.1, running on a MacBook Pro i9 32 GB macOS Catalina

Process:               Sketch [5496]
Path:                  /Applications/Sketch.app/Contents/MacOS/Sketch
Identifier:            com.bohemiancoding.sketch3
Version:               59.1 (86144)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sketch [5496]
User ID:               501

Date/Time:             2019-10-23 17:14:44.149 +0200
OS Version:            Mac OS X 10.15 (19A602)
Report Version:        12
Bridge OS Version:     4.0 (17P572)

**Comment by oodesign** [comment]
Hi @currocejudo,

Sorry to hear that is not working for you! Looks like a bug generating the previews, but we're not able to reproduce it with our testing set, though.

May you please send us your design files and related external libraries? You may do so here or send us a mail to to oscar@oodesign.me with the files or links to download them.

Thanks!

**Comment by dblooom** [comment]
Crash also here on Mac OS Catalina 10.15 and Sketch 59.1. Styler Plugin V 1.3.1.

Created a blank document with two rectangles. Then Sketch crashed. So crash seems not depending on files.

Here's a part of the crash log:

> Process:               Sketch [3958]
> Path:                  /Applications/Sketch.app/Contents/MacOS/Sketch
> Identifier:            Sketch
> Version:               59.1 (86144)
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           Sketch [3958]
> User ID:               501
> 
> Date/Time:             2019-10-24 22:14:27.829 +0200
> OS Version:            Mac OS X 10.15 (19A602)
> Report Version:        12
> Anonymous UUID:        0DE7D3FF-BF8A-5AEC-45C7-722CB47C127D
> 
> 
> Time Awake Since Boot: 3800 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        8  Dispatch queue: MSMetalRenderer rendering queue (QOS: USER_INTERACTIVE)
> 
> Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
> Exception Codes:       0x0000000000000001, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Signal:    Illegal instruction: 4
> Termination Reason:    Namespace SIGNAL, Code 0x4
> Terminating Process:   exc handler [3958]
> 
> Application Specific Information:
> ’|¥êˇˇ
> 

I'll sent the complete log to your email above.

**Comment by barmallion** [comment]
Same problem. Create new file, 1 Artboard, 2 textlayers. All plugins disabled.  Catalina 10.15 (19A602), Sketch 59.1

**Comment by oodesign** [comment]
Hi!

We're currently investigating some issues causing Styler to crash in Catalina.

I'll be happy to let you know when we release a fix.

Thanks for your feedback, and we apologize for any inconvenience this may cause.

**Comment by oodesign** [comment]
Hi @currocejudo @dblooom @barmallion ,

We just released v1.3.2, which hopefully fixes the issue causing Styler to crash on macOS Catalina.

May you give it a try and let us know how it worked for you?

Thanks!

**Comment by dblooom** [comment]
check my reply on Twitter :)
