### ISSUE TITLE
Crashing all the time

### ISSUE THREAD

**Issue by Stanleylee01** [oodesign/sketch-styler#4]
Can't work on sketch v59

**Comment by oodesign** [comment]
Hi @LeeSurelee ,

Unfortunately we can't reproduce the issue you describe. May you send us some more detailed information (Sketch version -59 or 59.1 -, macOS version ), and some further explanation of the crash?

Does it happen with any Sketch file? When does the crash occur? Are you able to see the Styler window and run a search, or does it crash just when triggered?

May you attach or send us to oscar@oodesign.me a Sketch file where it happens?

Thanks!

**Comment by oodesign** [comment]
Hi @LeeSurelee ,

Did it get any better, or are you still having issues with Styler?

Thanks!
