### ISSUE TITLE
Trial Expired

### ISSUE THREAD

**Issue by chaosplan** [oodesign/sketch-styler#5]
This looks like a great tool for my workflow.

When I was in Trial Mode the plugin was crashing. It looks like you've made some updates to fix the issue but now the Trial has timed out.

Is there any way to try this again? I'd gladly pay for the product if fills my needs.

**Comment by oodesign** [comment]
Hi @chaosplan,

Sorry for the late reply! 🙈

We're trying to keep this space just for technical issues related with the plugin.
If you're still interested in Sketch Styler, may I ask you to send me an e-mail to oscar@oodesign.me so that we can keep the conversation there?

Thanks!
