### ISSUE TITLE
Doesn't work in Sketch 60.1

### ISSUE THREAD

**Issue by dlewand691** [oodesign/sketch-styler#6]
Hello! I tried using the plugin in Sketch 60.1 on a large design system library and it crashed Sketch. So I tried using it on a new document with only 1 text layer and 1 text style. It couldn't find the style in the document and also crashed Sketch when also searching another library.

**Comment by oodesign** [comment]
Hi @dlewand691  ,

Sorry to hear that! Unfortunately we can't reproduce the issue you describe with our testing sets. May you send us some further details about the environment and the crash?

- What MacOS version are you on? 
- Does it happen with any Sketch file? When does the crash occur? Are you able to see the Styler window and run a search, or does it crash just when triggered?
- Does it happen with any linked library? Or just a specific one? If it's just that one, may you try to open it and run Styler directly on it?

May you attach or send us to oscar@oodesign.me a Sketch file & library where it happens?

Thanks!
