### ISSUE TITLE
Sketch keeps crushing

### ISSUE THREAD

**Issue by digital-service-marek-czyz** [oodesign/sketch-styler#7]
Hi,

Just downloaded the plugin and I can't access the main window with all the styles are listed and in addition to that the plugin keeps crashing Sketch. I'm on the latest version 61.2. Please help.

Cheers

**Comment by oodesign** [comment]
Hi @digital-service-marek-czyz ,

Sorry to hear that! Unfortunately we can't reproduce the issue you describe with our testing sets. May you send us some further details about the environment and the crash?

What MacOS version are you on?
Does it happen with any Sketch file? When does the crash occur? Are you able to see the Styler window and run a search, or does it crash just when triggered?
Does it happen with any linked library? Or just a specific one? If it's just that one, may you try to open it and run Styler directly on it?
May you attach or send us to oscar@oodesign.me a Sketch file & library where it happens?

Thanks!

**Comment by digital-service-marek-czyz** [comment]
Hi,

Thanks for getting back to me.

So below a few details and screen grab attached:

1. MacOS – Catalina 10.15.1
2. Yes, it happens with a few Sketch files. 
3. The crash occurs when I try do to pretty much anything with the plugin.
4. I can't see the Styler window
5. I'm not using libraries
6. Sorry but I can't send any of my files

I took a screen grab with the list from the plugin inside Sketch. Not much there to be honest. And the keyboard shortcut to trigger the main Styler window doesn't work at all. 

Thanks
![Screenshot 2019-12-25 at 11 07 04](https://user-images.githubusercontent.com/59202510/71442659-3115fb80-2707-11ea-95b9-290ebc1bc04a.png)

**Comment by oodesign** [comment]
Hi @digital-service-marek-czyz ,

May I ask which version of Sketch Styler are you using?

You may find it in the "Manage plugins" window, next to the plugin name.

Thanks!

**Comment by oodesign** [comment]
Hi @digital-service-marek-czyz ,

Are you still having issues with Styler?
If so, may you indicate us which Sketch Styler version are you using?

Thanks!

**Comment by fbchrt** [comment]
Hello @oodesign,

I have a similar issue: I see Styler's main search window, I then select the correct search parameters and hit "search": I Instantly get the beachball, and even after some time Sketch does not recover. I'm testing it with quite the extensive Text Style library (~6000 or so), and I suspect Styler is not able to deal with that?

Other possibility could be, that it is an Abstract library?

I was very happy when I found Styler and would love to pay for it - if it worked.

Any help appreciated!

**Comment by oodesign** [comment]
Hi @dorian-grey ,

Yup, 6.000 styles is way above what Styler can handle right now 😅.
Our heavier tests are run using ~2.000 styles, and use to take around 5-6 minutes to process, and lot of CPU is still required in this cases.

We're working on performance improvements. As soon as we make any progress on it I'll be happy to let you know.

By the way, the file being an Abstract library shouldn't affect the plugin, but please let us know if you find any issue with it.

Thanks for getting in touch!

**Comment by oodesign** [comment]
Hi @dorian-grey ,

We just released v1.4.0 which, aside of several bug fixes, includes some performance improvements.

May you give it a try and let us know how it worked for you?

Thanks a ton! 🥰

**Comment by fbchrt** [comment]
Sure @oodesign!

Can I just re-download the trial?

**Comment by oodesign** [comment]
HI @dorian-grey ,

Absolutely. May you please [send us an e-mail](mailto:oscar@oodesign.me)? 
I'll be happy to provide you instructions to do so.

Thanks!
