### ISSUE TITLE
Nothing happen when your press "Find matching styles"

### ISSUE THREAD

**Issue by VictorienDotNet** [oodesign/sketch-styler#8]
Nothing happen when your press "Find matching styles". Sketch version : 62 (91390). Plugin up to date.

**Comment by oodesign** [comment]
Hi @VictorienDotNet  ,

Sorry to hear that! Unfortunately we can't reproduce the issue you describe with our testing sets. May you send us a screen recording of the issue and some further details about the environment?

- What MacOS version are you on?
- Does it happen with any Sketch file? 
- Does it happen with any linked library? 

May you attach or send us to oscar@oodesign.me a Sketch file & library where it happens?

Thanks!
